/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const LoveNote = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllNotes' : IDL.Func([], [IDL.Vec(LoveNote)], ['query']),
  'submitNote' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const LoveNote = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    'getAllNotes' : IDL.Func([], [IDL.Vec(LoveNote)], ['query']),
    'submitNote' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };